name: Copy Repository to Hosted Runner

on:
  push:
    branches:
      - main # Replace with your desired branch

jobs:
  copy-repo:
    runs-on: self-hosted # You can choose a different runner if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Start React App
      run: pm2 start npm --name "my-react-app" -- start

    - name: Save PM2 process list
      run: pm2 list
